

#ifndef HAL_ULTRASONIC_H_
#define HAL_ULTRASONIC_H_
#include "../common/std_types.h"
#include "../MCAL/gpio.h"
#define ULTRA_SONIC_PORT PORTD_ID
#define ECHO_PIN PIN6_ID
#define TRIGGER_PIN PIN7_ID
void Ultrasonic_init(void);
/*▪ Description:
▪ Initialize the ICU driver as required.
▪ Set up the ICU callback function.
▪ Set the direction for the trigger pin as output through
the GPIO driver.
▪ Inputs: None.
▪ Return: None*/
void Ultrasonic_Trigger(void);
/*▪ Description:
▪ Send the trigger pulse to the ultrasonic sensor.
▪ Inputs: None.
▪ Return: None.*/
uint16 Ultrasonic_readDistance(void);
/*▪ Description:
▪ Send the trigger pulse by using the Ultrasonic_Trigger
function.
▪ Start the measurement process via the ICU driver*/
void Ultrasonic_edgeProcessing(void);
/*▪ Description:
▪ This is the callback function called by the ICU driver.
▪ It calculates the high time (pulse time) generated by
the ultrasonic sensor.
▪ Inputs: None.
▪ Return: None.*/


#endif /* HAL_ULTRASONIC_H_ */
